# Generated by Django 2.1.4 on 2019-01-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profiles/icon_user.jpg', null=True, upload_to='profiles'),
        ),
    ]
